name: Python CI with Ruff and Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff coverage
      - name: Lint with Ruff
        # https://docs.astral.sh/ruff/integrations/#github-actions
        run: ruff check --output-format=github .
      - name: Run tests with coverage
        run: coverage run -m unittest CalcTest.py
      - name: Check code coverage
        run: coverage report -m --fail-under=100
